# Generated by Django 4.2.2 on 2023-06-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterStrategicStop', models.BooleanField(default=True)),
                ('filterCandlestickPattern', models.BooleanField(default=True)),
                ('filterIndexValue', models.BooleanField(default=True)),
                ('filterIndexTrend', models.BooleanField(default=True)),
                ('filterBuy', models.BooleanField(default=True)),
                ('filterSell', models.BooleanField(default=True)),
                ('filterWait', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='empty title', max_length=200)),
                ('strategyType', models.CharField(default='empty strategyType', max_length=200)),
                ('signalType', models.CharField(default='empty signal type', max_length=200)),
                ('cover', models.CharField(default='empty cover', max_length=200)),
                ('footnote', models.CharField(default='empty footnote', max_length=200)),
                ('explanation', models.CharField(default='empty explanation', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=1000)),
                ('fulfilled_strategies', models.ManyToManyField(blank=True, related_name='fulfilled_series', to='api.strategycard')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('strategies', models.ManyToManyField(blank=True, related_name='deck_strategies', to='api.strategycard')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=1000)),
                ('strategies', models.ManyToManyField(blank=True, related_name='strategy_series', to='api.strategycard')),
            ],
        ),
    ]
